### PR TITLE
Add link and screenshot to Silverjuke, an FOSS jukebox which is also …

### PR DESCRIPTION
**Pull request by r10s**
…proudly using projectM :)

### CODE REVIEW

**Comment by revmischa** [comment]
great! 👍

**Comment by r10s** [comment]
thank you - also for your great visualization :)

**Comment by revmischa** [comment]
like the new autotools system?

**Comment by r10s** [comment]
Looks good to me, however, in practise, I have not tried it yet myself. In fact, I have not much time left for Silverjuke these days (fully occupied with Delta Chat), I've just fixed a few urgent bugs Silverjuke so that the upcoming Ubuntu release gets a version that is working fine. By this, I noticed that projectM is very busy these days :) which is great - I use the visualisations in Silverjuke every day :)
BTW: You/projectM is also mentioned in the "About box" of Silverjuke for years :) Again - thank you very much for the great work!

**Comment by revmischa** [comment]
Appreciate it! I mostly just maintain it, I didn't do most of it myself. I've been trying to get it modernized and cross-platform and respond to peoples' questions and issues. Just started an IRC channel, #projectM on freenode if you want to join

**Pull request merged**
