### PR TITLE
Merge MilkDrop2 source

### PR DESCRIPTION
**Pull request by mancoast**
Merge the MilkDrop2 source into this codebase. Continue development of this plugin's DLL for Winamp at this centralized community.

### CODE REVIEW

**Comment by mancoast** [comment]
@PeterMalkin Is it possible for you to contact Ryan again? We require authorization from Geiss to merge the code from https://sourceforge.net/p/milkdrop2/code/ci/master/tree/ because I do not see the License anywhere on sourceforge or http://www.geisswerks.com/milkdrop/

**Comment by dr0biwan** [comment]
You probably don't need Ryan's permission since all of the Winamp related code that was released including Milkdrop was done under a zlib/bsd-like license or just a do as you wish & don't misappropriate the origins of the code.

Also https://sourceforge.net/projects/milkdrop2/ is clearly listed under a BSD license even if no specific license file was included in the repository :)

-dro

**Comment by revmischa** [comment]
Perhaps consider using git subtree - it keeps the history intact from the old repo.
Not submodule which is wack and broken but subtree. 
https://stackoverflow.com/questions/32407634/when-to-use-git-subtree

**Comment by revmischa** [comment]
Can you please try to do a subtree merge instead?

**Comment by mancoast** [comment]
I thought I did, but it must have done a rebase? Can you handle it and do the force push? I do not want to force push. That’s my mistake, whoops!

**Comment by mancoast** [comment]
@revmischa (please see notes above TL;DR; The history of this repo is preserved, I think it was due to the accidental rebase?) do you want to use subtree merge instead?  Are you OK with the rebase and merge from rg's branch on sourceforge or should we plan a force push to master branch to rework?

**Comment by mancoast** [comment]
@dr0biwan I somehow missed the BSD info on sourceforge, but a second glance and its right there in the middle of the landing page.  I appreciate your pointers there and the sanity check.  Thanks, coast

**Comment by revmischa** [comment]
Sorry, where can I see the history of these files? I don't see any commits except for "initial commit" on randomly selected files
https://github.com/projectM-visualizer/projectm/commits/1c02be05605219b87fb75834bb5daa16eb331a6a/src/Winamp/VIS.H

**Comment by mancoast** [comment]
@dr0biwan maybe you know more inside info? But as far as I know, the entire history of the files is closed source, and they were set free to open-access exactly like that by Geiss on sourceforce in 2013 with a single GIT commit.

**Comment by mancoast** [comment]
@revmischa check this our here: https://sourceforge.net/p/milkdrop2/code/ci/f05b0d811a87a17c4624170c26c93bac39b05bde/

**Comment by dr0biwan** [comment]
@mancoast there was only ever what was committed by Ryan which would have come from a simple zip archive at the time.
The commit history wouldn't have been provided & even if done it would have been more effort than people were wanting to do since it would have been split over CVS, SVN & possibly an internal git repository at the time (even the current owners of Winamp didn't get a copy of the commit history when it was sold to them & you're unlikely to have AOL do anything assuming they kept any of those around in the almost 6 years since).
I'd just take the code that you've got access to & move on & do whatever it is you're actually going to do with it.
-dro

**Comment by revmischa** [comment]
I see, ok

**Pull request merged**
