### PR TITLE
Upgrade LLVM JIT

### PR DESCRIPTION
**Pull request by revmischa**
For new LLVM version (9+)
Doesn't quite work. Need help.

### CODE REVIEW

**Comment by labkey-matthewb** [comment]
Hi Mischa, I made a similar change a few weeks ago when I upgrade a machine to Ubuntu 20.04.  In addition to these few changes, I had to change the build to use c++14.  That is why I didn't immediately create a PR, because I don't really know the implications of that.

See this commit on branch llvm_10:

https://github.com/projectM-visualizer/projectm/commit/58e0a516edb6848011786572e6bb216b62011f38

**Comment by revmischa** [comment]
When I ran it with my changes I get bad access crash when it initializes the engine
`ExecutionEngine* executionEngine = EngineBuilder(std::move(jitx.module_ptr)).create();`

**Comment by labkey-matthewb** [comment]
> When I ran it with my changes I get bad access crash when it initializes the engine
> `ExecutionEngine* executionEngine = EngineBuilder(std::move(jitx.module_ptr)).create();`

Maybe some subtle difference between llvm::make_unique/move and std::make_unique/move?  (I haven't looked inside the implementation)

**Comment by revmischa** [comment]
Done in #470 and https://github.com/kblaschke/projectm/commit/0dc7efedec809de42bacac208f1f6da2a150566d

**Pull request closed without merging**
