### PR TITLE
Preset subdirs

### PR DESCRIPTION
**Pull request by revmischa**
Recursively scan presets directory for presets.

This makes managing presets simpler because we can preserve an organized structure and don't have to copy thousands of files to a single directory.

The code, build options, install steps are all simplified.

Refactored the directory scanning code, added optimized posix version, made it used by texture loading and preset loading.

### CODE REVIEW

**Comment by revmischa** [comment]
However, fts doesn't exist on windows :(
Maybe we need something like https://rosettacode.org/wiki/Walk_a_directory/Recursively#Windows

**Comment by revmischa** [comment]
@milkdropper @coast77777777777  I'm getting this from the Windows build - does the VCProj need to be updated somehow?
```
         projectM.lib(PresetLoader.obj) : error LNK2019: unresolved external symbol "public: __cdecl FileScanner::FileScanner(void)" (??0FileScanner@@QEAA@XZ) referenced in function "public: __cdecl PresetLoader::PresetLoader(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0PresetLoader@@QEAA@HHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\projects\projectm\msvc\projectMSDL.vcxproj]
         projectM.lib(PresetLoader.obj) : error LNK2019: unresolved external symbol "public: __cdecl FileScanner::FileScanner(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (??0FileScanner@@QEAA@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@0@Z) referenced in function "public: __cdecl PresetLoader::PresetLoader(int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0PresetLoader@@QEAA@HHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\projects\projectm\msvc\projectMSDL.vcxproj]
         Renderer.lib(TextureManager.obj) : error LNK2001: unresolved external symbol "public: __cdecl FileScanner::FileScanner(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (??0FileScanner@@QEAA@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@0@Z) [C:\projects\projectm\msvc\projectMSDL.vcxproj]
         projectM.lib(PresetLoader.obj) : error LNK2019: unresolved external symbol "public: void __cdecl FileScanner::scan(class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)>)" (?scan@FileScanner@@QEAAXV?$function@$$A6AXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@std@@@Z) referenced in function "public: void __cdecl PresetLoader::rescan(void)" (?rescan@PresetLoader@@QEAAXXZ) [C:\projects\projectm\msvc\projectMSDL.vcxproj]
         Renderer.lib(TextureManager.obj) : error LNK2001: unresolved external symbol "public: void __cdecl FileScanner::scan(class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)>)" (?scan@FileScanner@@QEAAXV?$function@$$A6AXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@std@@@Z) [C:\projects\projectm\msvc\projectMSDL.vcxproj]
         projectM-sdl\Release\projectM.exe : fatal error LNK1120: 3 unresolved externals [C:\projects\projectm\msvc\projectMSDL.vcxproj]
```

**Comment by milkdropper** [comment]
This is great!

**Comment by revmischa** [comment]
Linking on windows is failing 
```
       "C:\projects\projectm\src\EyeTune\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.vcxproj" (default target) (2) ->
       (Link target) -> 
         PresetLoader.obj : error LNK2001: unresolved external symbol "public: void __cdecl FileScanner::scan(class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)>)" (?scan@FileScanner@@QEAAXV?$function@$$A6AXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@std@@@Z) [C:\projects\projectm\src\EyeTune\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.vcxproj]
         PresetLoader.obj : error LNK2001: unresolved external symbol "public: __cdecl FileScanner::FileScanner(void)" (??0FileScanner@@QEAA@XZ) [C:\projects\projectm\src\EyeTune\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.vcxproj]
         PresetLoader.obj : error LNK2001: unresolved external symbol "public: __cdecl FileScanner::FileScanner(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > &)" (??0FileScanner@@QEAA@AEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@0@Z) [C:\projects\projectm\src\EyeTune\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.vcxproj]
         C:\projects\projectm\src\x64\Release\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.dll : fatal error LNK1120: 3 unresolved externals [C:\projects\projectm\src\EyeTune\projectM.WindowsUniversal.SharedLibrary\projectM.WindowsUniversal.SharedLibrary.vcxproj]
```
I don't have windows so not sure how to address this. Need some help.

**Comment by milkdropper** [comment]
That's a lot of great progress. I'll take a look at the windows issue tomorrow.

**Comment by milkdropper** [comment]
This worked out of the box for me. I am using Microsoft Visual Studio Community 2019 on Windows 10. I downloaded the branch, opened the msvc project file, and compiled SDL.

I also confirmed the recursive preset folder is working for me by putting a single preset in presets/part1 and a single preset in presets/part2. I see them both loading.

**Comment by revmischa** [comment]
> This worked out of the box for me. I am using Microsoft Visual Studio Community 2019 on Windows 10. I downloaded the branch, opened the msvc project file, and compiled SDL.
> 
> I also confirmed the recursive preset folder is working for me by putting a single preset in presets/part1 and a single preset in presets/part2. I see them both loading.

Cool, not sure what's wrong with appveyor

**Pull request merged**
