### PR TITLE
OpenGL ES 3.0 support

### PR DESCRIPTION
**Pull request by deltaoscarmike**
Modernization of openGL calls: now it is compliant to GL 3.2+ and GLES 3.0+ core profiles.

To check for correctness of this port, I've compared the behavior of each preset builtin variables for openGL 3.2 and openGL ES 3.0 profiles vs the previous rendering results. 
All openGL calls have been ported and are functional.

Not working (in priority order):
FBO: some tests needs to be completed to check for correctness
Cg: next step is the integration with @revmischa HLSL->GLSL translation
FTGL: no openGL ES support, is it worth it ? (alternative candidate: http://cdave1.github.io/ftgles/)

### CODE REVIEW

**Comment by revmischa** [comment]
This is really great, thanks so much. I want to help get this merged and tested and building on all platforms and integrated with the HLSL->GLSL shader stuff.
I made a couple small improvements https://github.com/projectM-visualizer/projectm/commit/25131614891ed5d9ccb7edd784b0d64582c38502

Are you on IRC? Slack? Can we chat somewhere?

**Comment by deltaoscarmike** [comment]
I have a Slack account, how to proceed ?

**Comment by revmischa** [comment]
@deltaoscarmike http://slack.llolo.lol/

**Comment by revmischa** [comment]
gcc-7 seems to be complaining about gles headers https://travis-ci.org/projectM-visualizer/projectm/jobs/389361834#L1518

**Comment by revmischa** [comment]
```
In file included from ShaderEngine.hpp:12:0,
                 from ShaderEngine.cpp:9:
../../../src/libprojectM/projectM-opengl.h:15:12: fatal error: GLES3/gl32.h: No such file or directory
 #  include <GLES3/gl32.h>
            ^~~~~~~~~~~~~~
```

**Comment by revmischa** [comment]
Merging to projectM/gles3 - feel free to push directly to this branch instead of your clone

**Pull request merged**
