### PR TITLE
Mention ProM in readme for LV2 + VST2 audio plugin project

### PR DESCRIPTION
**Pull request by falkTX**
It is nearly complete and release will be made soon.

### CODE REVIEW

**Comment by falkTX** [comment]
I will have to setup some things on the framework side first, to make sure we can pack and load resources from the correct location.
This will take a few days/weeks.

**Comment by kblaschke** [comment]
No progress here for a long time, so I converted the PR to a draft. If you're done with your project, feel free to bring it up when it's ready!

**Comment by kblaschke** [comment]
Since much has changed in libprojectM: I'd not recommend using the approach of compiling projectM in your plug-in's Makefile, becuase it's easy to miss some preprocessor directives and other stuff. You might want to consider using the CMake-based build and then link the resulting static library and change the calls to the internal C++ classes to the new public C API, as this will be more stable (there's still a lot of internal refactoring planned, to you'd have to rewrite your Makefile and code quite often, possibly even on patch releases, while the public API should not change much). Might even be worthwhile to swap your Makefiles with CMakeLists.txt so you can use CMake's dependency resolving and build system project generator features.

**Comment by kblaschke** [comment]
Closing the PR due to inactivity.
If you've fixed your issues and want the link in the ReadMe, please open a new PR or rebase & reopen this one.

Besides that, the Wiki has a page with third-party apps which you can simply edit without a PR:
https://github.com/projectM-visualizer/projectm/wiki/projectM-Applications#applications-by-third-party-developers

**Pull request closed without merging**
