### PR TITLE
Fix bug in Windows.

### PR DESCRIPTION
**Pull request by milkdropper**
Can you merge this into master? The config PR submitted by @ycollet seems to have problems. It causes crashes for me on Windows. I think it's because the homedir was backwards, and it aborts without a config when it should continue with built-in config.

### CODE REVIEW

**Comment by revmischa** [comment]
Feel free to merge if tests pass

**Comment by milkdropper** [comment]
Should I be able to merge it in? I don't see the option. I think I let to your request to collaborate expire (I didn't notice it).

**Comment by milkdropper** [comment]
Great - I see it now! What standard operating procedures would you like me to follow (beyond checking tests)?

**Comment by revmischa** [comment]
Up to you. We could always use more automated tests in CI. Adding a test for checking if static linking of SDL2 or compilation of aligned alloc works would be super cool. More Qt compile tests

**Pull request merged**
