### PR TITLE
Native presets

### PR DESCRIPTION
**Pull request by revmischa**
Build and install native presets (aka .so/.dylib shared object files for presets instead of milkdrop equations)

### CODE REVIEW

**Comment by schnitzeltony** [comment]
I am preparing build of 2.2.1 with Openembedded for embedded linux system. The build system is not happy, installing libraries in /usr/share/...
Would it be possible to put them at /usr/lib/projectm/presets or similar?

**Comment by revmischa** [comment]
Sure, patches welcome! 
Just curious - does it work on embedded? It doesn't support GLES (yet)

**Comment by schnitzeltony** [comment]
Haven't seen it running yet but did not spend too much time on it. Am building for Raspi VC4 (open source/mesa) and that supports OpenGL 2.1 - don't know which limitations there are.
One question: regarding my original question: We have now native presets (=libs) and the milk files (which are no more installed by default with 2.2.1). Are both still supported and if yes: How to get different locations handled?

**Comment by revmischa** [comment]
The milk files should be installed - to /usr/local/share/projectM/presets. Are they not?
projectM probably won't run on any embedded systems until GLES support is added - https://lwn.docx.pro/q6IHamrUd

**Comment by revmischa** [comment]
If I do:
`./configure --prefix=$PWD/t --enable-shared=no --enable-sdl --enable-cg`
and then `make install`
```
$ ls -l t/share/projectM/presets/ | wc -l
    1996
```

**Comment by revmischa** [comment]
Alright, I do warn you again that GLES is needed for it to work on an embedded system - https://github.com/projectM-visualizer/projectm/issues/11

The relevant preset install target is in the root Makefile.am:
```
# aka /usr/local/share/projectM
pm_data_dir = $(pkgdatadir)
pm_font_dir = $(pm_data_dir)/fonts
pm_presets_dir = $(pm_data_dir)/presets
pm_shaders_dir = $(pm_data_dir)/shaders

pm_data__DATA = src/libprojectM/config.inp
pm_font__DATA = fonts/Vera.ttf fonts/VeraMono.ttf
pm_shaders__DATA = src/libprojectM/Renderer/blur.cg \
                   src/libprojectM/Renderer/projectM.cg

install-data-local:
	test -z $(pkgdatadir) || $(MKDIR_P) $(pm_presets_dir)
	find "$(PRESETSDIR)" -type f -exec $(INSTALL_DATA) {} $(pm_presets_dir) \;
```

However, projectMSDL currently has settings hard-coded. There's an issue to make it use the normal config file (#29). It looks for the fonts etc from the current directory of the SDL executable right now. It needs to be changed to use the paths in a config file.

**Pull request merged**
