### PR TITLE
Qt5

### PR DESCRIPTION
**Pull request by revmischa**
This is almost ready to merge!

### CODE REVIEW

**Comment by revmischa** [comment]
Seems to build and install fine from source, but tries to recurse (incorrectly) into projectm-qt when building from dist tarball, is what it looks like?

**Comment by revmischa** [comment]
```
make[3]: Leaving directory `/home/travis/build/projectM-visualizer/projectm/src/projectM-sdl'
 (cd projectM-qt && make  top_distdir=../../projectM-2.2.0 distdir=../../projectM-2.2.0/src/projectM-qt \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/home/travis/build/projectM-visualizer/projectm/src/projectM-qt'
make[3]: *** No rule to make target `distdir'.  Stop.
make[3]: Leaving directory `/home/travis/build/projectM-visualizer/projectm/src/projectM-qt'
make[2]: *** [distdir] Error 1
```

**Comment by deltaoscarmike** [comment]
Automake needs more tweaking:
[https://github.com/deltaoscarmike/projectm/commit/f79b682f006c1bf9cf0c588f90e329b1268b71f5](https://github.com/deltaoscarmike/projectm/commit/f79b682f006c1bf9cf0c588f90e329b1268b71f5)

I don't know how to submit patch to a pull request.
Do I have to create a new pull request ?

**Comment by revmischa** [comment]
you can create a PR and set the base to "qt"

**Comment by revmischa** [comment]
I'm ready to merge whenever you say it's good. I haven't tried building with qt yet. We should add it to travis

**Comment by deltaoscarmike** [comment]
Thanks

**Pull request merged**
