### PR TITLE
Add get and Set for beat sensitivity value to API

### PR DESCRIPTION
**Pull request by kockie69**
In my battle to get the code change through it looks like previous PR disappeared. 
This version has been tested and linked correctly for me.

### CODE REVIEW

**Comment by kblaschke** [comment]
> In my battle to get the code change through it looks like previous PR disappeared. This version has been tested and linked correctly for me.

I suggest using a working branch instead of working directly on master, this makes it easier to keep your fol up to date, rebase multiple working branches on the upstream changes etc., and it's probably the reason GitHub gets confused of you reset the master branch, leading to an autoclose of the PR.

There's two identical commits and an unnecessary merge commit here. Of you could manage to remove one of the duplicate commits and the merge commit, it's fine!

If you can't figure out how to clean the branch up, I can do that for you.

**Review by kblaschke — CHANGES_REQUESTED** [review]
Delete duplicate and merge commit, then it's ready to merge!

**Comment by kockie69** [comment]
Can you have a look please and fix. Next time I will work from a separate branch.

**Comment by kblaschke** [comment]
> Can you have a look please and fix. Next time I will work from a separate branch.

No need, it's perfect! Thanks for your contribution!

**Review by kblaschke — APPROVED** [review]
Changes are all good now! Waiting for the builds to complete, will merge afterwards.

**Pull request merged**
