### PR TITLE
GStreamer (WIP)

### PR DESCRIPTION
**Pull request by revmischa**
### Work in progress
* wrapper application which lets you specify an input file/url to read from
* gstreamer element which renders the visual

## Help Wanted
If you are familiar with gstreamer, please help make this work!

### CODE REVIEW

**Comment by coast77777777777** [comment]
what is gstreamer? does this work with appleTV? does this work with chromecast? Some leverage chromecast and appletv for music. How can we support those end users?

**Comment by revmischa** [comment]
GStreamer is an amazing multimedia library that can do a lot with setting up routing of audio and video https://gstreamer.freedesktop.org/documentation/?gi-language=c

Personally I'd love to have this working so I can feed in an audio file and output a movie file (for #205). It would enable all kinds of uses for projectM, allowing it to be placed anywhere in any sort of media pipeline someone could dream up.

**Comment by coast77777777777** [comment]
Ok this makes sense to me now. I have been recording the hdmi signal using hardware. I am curious the system requirements to record some 4K while generating a smooth 60fps.

**Comment by kblaschke** [comment]
Might still make sense to add this as an external support library in the project, closing for now since it's stale & hard to rebase on current master.

**Pull request closed without merging**
