### PR TITLE
Fix CMake options

### LINKED ISSUE #524: Cmake -DENABLE_GLES=OFF -DENABLE_SDL=OFF do nothing
**Describe the bug**
Project still tries to find sdl2 & gles if they are disabled via cmake.

**Screenshots**

**Desktop (please complete the following information):**
 - Application: n/a
 - OS: openSUSE Tumbleweed
 - Version: master.

**Additional context**

### PR DESCRIPTION
**Pull request by kblaschke**
Some options weren't evaluated correctly regarding the dependencies. Also added a failure notice if GLES is enabled, as the CMake find module is still missing/unimplemented.

Fixes #524.

### CODE REVIEW

**Comment by DAP-DarkneSS** [comment]
fatal error: GLES3/gl3.h: No such file or directory
[_log.txt](https://github.com/projectM-visualizer/projectm/files/6981088/_log.txt)

**Comment by revmischa** [comment]
Any way to add a test for this in the CI build phase? The more options we can cover with GHA the better IMO

**Comment by kblaschke** [comment]
> Any way to add a test for this in the CI build phase? The more options we can cover with GHA the better IMO

Sure thing. GLES support in CMake isn't complete though, as detecting includes and libraries required for this is _very_ platform/implementation specific and thus the main reason why CMake's FindOpenGL module is still missing support for it.

I'll see if I can add a find module for GLES3 that covers the main build platforms (Windows, MacOS, Linux and Android) and get it built via CI. AFAIR the GitHub Win/Linux runners have Android SDK/NDK installed, so we might be able to test this platform as well.

**Comment by kblaschke** [comment]
> fatal error: GLES3/gl3.h: No such file or directory
> [_log.txt](https://github.com/projectM-visualizer/projectm/files/6981088/_log.txt)

Missed one `#ifdef` in projectM-opengl.h, this should fix it.

**Comment by DAP-DarkneSS** [comment]
> Missed one `#ifdef` in projectM-opengl.h, this should fix it.

Thank you very much! Is built fine now.

**Comment by revmischa** [comment]
Just tested this branch on macOS and all is looking good!

**Review by revmischa — APPROVED** [review]

**Pull request merged**
