### PR TITLE
Fixes "libprojectm: Qt PulseAudio CMake wrong linker path" Issue #543

### PR DESCRIPTION
**Pull request by rorypierce**
I view my relationship with CMake as more hate than love; however, it's pretty okay 8^)... @digitalcircuit thanks for the very helpful documentation! I was super-frustrated that I couldn't get the non-SDL rendering to work (only ~25fps)--now it's supah-High! This project is fantastic!

### CODE REVIEW

**Comment by rorypierce** [comment]
I went after trying to eliminate the header `include` error in the CI/AppVeyor build; however, it looks like my initial guess for correction was incorrect. Forced update {I'm the only individual working on this PR; so it's okay} focus on the bare-minimum, necessary commits only.

**Comment by revmischa** [comment]
I'm not sure what the state of the Appveyor build is; is it using cmake? @kblaschke @milkdropper ?

**Review by kblaschke — CHANGES_REQUESTED** [review]

**Comment by kblaschke** [comment]
@rorypierce you want to remove the superfluous `CMAKE_DL_LIBS` lines from your commit, or should I? We could then immediately merge this PR.

**Comment by rorypierce** [comment]
Hi Kai,

Sorry been so busy. I imagine you already performed the change. I'll try to
re-fetch from the upstream and check it out. Thanks!
Rory

**Comment by kblaschke** [comment]
> Hi Kai, Sorry been so busy. I imagine you already performed the change. I'll try to re-fetch from the upstream and check it out. Thanks! Rory

No prolem! If that worked out for you, either close this PR or amend your commits for any further changes that may be required.

**Pull request closed without merging**
