### PR TITLE
Setter and Getter for beat sensitivity

### PR DESCRIPTION
**Pull request by kockie69**
This will add the possibility to change the beat sensitivity by calling projectm_set_beat_sensitivity instead of using the key handler.

### CODE REVIEW

**Comment by kblaschke** [comment]
Looks great so far, thanks!

Just two small requests:
- Please edit the commit message (and PR title) to state what each does. "First version" isn't really necessary. Something like "Add setter for beat sensitivity value to API".
- When adding a setter, please also add an accompanying getter function (`projectm_get_beat_sensitivity`) so applications can also get the current value easily, e.g. for incrementing/decrementing and removing the necessity to redundantly store the value on the application side. Just add another commit as the aboce with the getter method.

**Review by kblaschke — CHANGES_REQUESTED** [review]
Just two small requests:
- Please edit the commit message (and PR title) to state what each does. "First version" isn't really necessary. Something like "Add setter for beat sensitivity value to API".
- When adding a setter, please also add an accompanying getter function (`projectm_get_beat_sensitivity`) so applications can also get the current value easily, e.g. for incrementing/decrementing and removing the necessity to redundantly store the value on the application side. Just add another commit as the above with the getter method.

**Comment by kockie69** [comment]
I have changed the title and have added a getter

**Comment by kblaschke** [comment]
> I have changed the title and have added a getter

Could you also update the commit message of your first commit, please? Thanks!

**Pull request closed without merging**
