### PR TITLE
Preset subdirs

### PR DESCRIPTION
**Pull request by nttan2805**
sdfsdfsdfsdfsdfsdfsd

### CODE REVIEW

**Comment by revmischa** [comment]
This was already merged to master in https://github.com/projectM-visualizer/projectm/commit/e49720ecfa19d760fb5b6d9f9afad3dbbb43d814

**Comment by revmischa** [comment]
Did your cat open this PR?

**Comment by milkdropper** [comment]
I am a humble noob with github. If I reopened this PR accidentally, can you safely remerge? If not I will test my luck.

**Comment by milkdropper** [comment]
Oh nevermind - I think it was @nttan2805?

**Comment by revmischa** [comment]
Closing this as the worst PR of all time

**Pull request closed without merging**
