### PR TITLE
include the 52k preset pack from winamp forums

### PR DESCRIPTION
**Pull request by otherdev98**
This pull request includes the milkdrop text files from the mega preset pack, this PR omits all the textures.
also, some/many of these presets have inappropriate names, this should be discussed before merging into the code.

### CODE REVIEW

**Comment by bebop210** [comment]
Is anyone testing these out one by one yet? I’ll take a pack of them I just had to get my Linux install going.. but now I have projectm on my manjaro Deepin, a windows 7 running kodi with projectm + milkdrop2 and an android tv box with projectm pro

**Comment by bebop210** [comment]
Also about the names, curse words vs drug references? One can easily be changed with * syntax the other you’re censoring intent which is a completely different animal.

**Comment by revmischa** [comment]
Don't change the fucking names! imo

**Comment by coast77777777777** [comment]
Greetings @otherdev98 , I agree with you @revmischa and I think it’s important to preserve the artistic design intent. I also agree that some of these preset names are not appropriate for our public facing community. This situation is complicated, and I do not suggest to know how to solve it, but I hope we can figure this one out, because I think the large amount of authors and presets here are worthwhile to explore. Any thoughts?

**Comment by revmischa** [comment]
They seem entirely appropriate to me. What's the concern? Somebody will see that their visualization has the word Psilocybin in the name and then go purchase mushrooms and do them and watch projectM?
Jolly good, I say.

**Comment by coast77777777777** [comment]
In my opinion, the drug references are inappropriate, but I am also concerned about the references to violence and other themes in some of these file names. I have really enjoyed this community, but some things I cannot associate with because it’s against my personal code of conduct. While I'm worried about the end users seeing the file names, I am also worried about future collaboration/employers that analyze GitHub datasets. The risk of being associated with violence and other filth might drive some devs away(like myself).  I already changed my username out of caution here, and it saddens me that the presets in this PR have these terrible file names because I feel like my dev efforts for projectM are just beginning and I don’t want to ghost. On the other hand, as a digital native, I think it’s wrong to censor the artistic work of others. Is there any room for middle ground here? Maybe we can author a contributor agreement with simple policies to resolve this type of conflict? Many GNU projects operate that way. Thoughts?

**Comment by revmischa** [comment]
I mean I don't have a really strong opinion, if you feel like a preset with a violent name would cause someone to associate the project with violence then go ahead and change the names.
I just personally am not concerned about this scenario for myself. If you are, you can change it.

**Comment by revmischa** [comment]
I appreciate your contributions @coast77777777777 and don't want you to 👻

**Comment by coast77777777777** [comment]
@revmischa Thanks dude! I love thinking back to good old milkdrop and avs nostalgia. Anyways, this might be easier to merge if we have a strategy or something like that to refer back to in the future?

**Comment by ravermeister** [comment]
why not sort the presets in different folders and let the user choose which folder for having generated from?
the default one could be with harmless filenames

**Comment by speakn2pabst** [comment]
I'm just someone who follows the project so I don't expect to carry a large voice in this conversation.  But I'd like to throw out another "middle ground" idea.  

Maybe include a disclaimer read.me (or similar) included with these files distancing ProjectM contributors from having created file names or original authorship of the presets.  Then the files would files live on as their original authors created them and they (the original creators) would be able to find/search for them across Git using the original names.  

So maybe just group these presets in a subdirectory called "Bad" or "Objectionable" and include the disclaimer file in there.  Or just include the disclaimer file and use whatever directory structure is best.

Again just an idea as an outside observer, I'll likely support any decision that is carried out.

**Comment by revmischa** [comment]
what do you think about tarring this directory up?

**Comment by coast77777777777** [comment]
this is not worth it

**Comment by ravermeister** [comment]
So the presets are not applied to projectM at all? that's sad...

**Comment by revmischa** [comment]
I would merge it if the presets were zipped

**Comment by ravermeister** [comment]
I will create a zip file containing the presets from the exe installer and post the link back. Just give me a day or two

**Comment by revmischa** [comment]
Sure, please open a new branch or remove the commit adding the 52k files because they will still be present in history otherwise

**Comment by ravermeister** [comment]
Ok, 
So I'll revert this PR in my master branch, and add the zip under:
`/bad_presets/mdpresets.zip` correct me if I'm wrong..

**Comment by revmischa** [comment]
sure, `52kpresets.zip` would be fine

**Comment by ravermeister** [comment]
hmmm.  Will provide the zip on sf.net because:
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 65d5c683c40f196063baa0b1989dbb02
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File bad_presets/52kpresets.zip is 174.21 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/ravermeister/projectm.git
 ! [remote rejected]     master -> master (pre-receive hook declined)

**Comment by ravermeister** [comment]
I was not able to push my master branch after adding the Zip file. it seems that github does not allow files >100MB inside a source repo (see error below). So I Uploaded the Zip file to Sourceforge.net:
https://sourceforge.net/projects/mdpresetpack/files/mdpresets.zip
(I symlinked to https://sourceforge.net/projects/mdpresetpack/files/52kpresets.zip)
`raver@viruspad:~/repos/projectm$ git push
Username for 'https://github.com': jonny@rimkus.it
Password for 'https://jonny@rimkus.it@github.com': 
Username for 'https://github.com': jonny@rimkus.it          
Password for 'https://jonny@rimkus.it@github.com': 
Objekte aufzählen: 6, Fertig.
Zähle Objekte: 100% (6/6), Fertig.
Delta-Kompression verwendet bis zu 4 Threads.
Komprimiere Objekte: 100% (4/4), Fertig.
Schreibe Objekte: 100% (4/4), 154.37 MiB | 38.00 KiB/s, Fertig.
Gesamt 4 (Delta 2), Wiederverwendet 0 (Delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 30fbcbc1b3e88df5a447f4654ef229e5
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File bad_presets/52kpresets.zip is 174.21 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/ravermeister/projectm.git
 ! [remote rejected]     master -> master (pre-receive hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/ravermeister/projectm.git'
`

**Comment by ravermeister** [comment]
See new PR: https://github.com/projectM-visualizer/projectm/pull/255

**Comment by revmischa** [comment]
See #259 ?

**Comment by coast77777777777** [comment]
I am scanning the files with code shown below. 


```

using Microsoft.Azure.CognitiveServices.ContentModerator;
using Newtonsoft.Json;
using RatiocinationLibrary;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;

namespace cognitiveContentModerator
{
    class Program
    {
        static int bad = 1;
        static int good = 0;
        static int glitch = -1;

        // TEXT MODERATION
        // Name of the file that contains text
        private static readonly string TextFile = "TextModerationInput.txt";

        // The name of the file to contain the output from the evaluation.
        private static string OutputFile = "TextModerationOutput.txt";
        private static readonly string mySubscriptionKey = "###############";
        private static readonly string myEndpoint = "https://eastus.api.cognitive.microsoft.com";

        static void Main(string[] args)
        {
            Log.Initialize();
            Print("Hello World");
            var files = ScanMilkDropFiles();


            // string raw_text = File.ReadAllText(TextFile);
            // var text_strings = raw_text.Split(System.Environment.NewLine.ToCharArray());
            
            
            // Load the input text.
            foreach (var i in files)
            {
                int decision = CognitivePostAPI(i);
                if (decision == good)
                    MoveGoodFile(i);
                if (decision == bad)
                    MoveBadFile(i);
                Thread.Sleep(100);
            }
        }

        private static void MoveBadFile(string path)
        {
            try
            {
                // To move a file or folder to a new location:
                //  D:\GIT\milkdrops\bad_presets\presets_untested --> presets_untested_bad
                var destinationPath = path.Replace("presets_untested", "presets_untested_bad");
                System.IO.Directory.CreateDirectory("D:\\GIT\\milkdrops\\bad_presets\\presets_untested_bad");
                File.Move(path, destinationPath);
            }
            catch (Exception e)
            {
                Log.Exception(e);
            }
        }

        private static void MoveGoodFile(string path)
        {
            try
            {
                // To move a file or folder to a new location:
                //  D:\GIT\milkdrops\bad_presets\presets_untested --> presets_untested_good
                var destinationPath = path.Replace("presets_untested", "presets_untested_good");
                System.IO.Directory.CreateDirectory("D:\\GIT\\milkdrops\\bad_presets\\presets_untested_good");
                File.Move(path, destinationPath);
            }
            catch (Exception e)
            {
                Log.Exception(e);
            }
        }

        private static List<string> ScanMilkDropFiles()
        {
            // scan
            string presetspath = "D:\\GIT\\milkdrops\\bad_presets\\presets_untested";
            DirectorySearch.Initialize("*", 1);
            //DirectorySearch.Initialize("*");
            DirectorySearch.SetSearchPath(presetspath);
            DirectorySearch.ProcessDirectory();
            var files = DirectorySearch.GetSearchList();
            return files;
        }

        static int CognitivePostAPI(string raw_text)
        {
            Print("Scanning : " + raw_text + 
                  " with cognitive API");
            try
            {
                var text = Path.GetFileName(raw_text).Replace(System.Environment.NewLine, " ");
                byte[] byteArray = System.Text.Encoding.UTF8.GetBytes(text);
                MemoryStream stream = new MemoryStream(byteArray);

                // Create a Content Moderator client and evaluate the text.
                using (var client = Clients.NewClient())
                {
                    // Screen the input text: check for profanity,
                    // autocorrect text, check for personally identifying
                    // information (PII), and classify the text into three categories
                    Log.TextEntry("Autocorrect typos, check for matching terms, PII, and classify.");
                    var screenResult =
                        client.TextModeration.ScreenText("text/plain", stream, "eng", true, true, null, true);
                    var cog = JsonConvert.SerializeObject(screenResult, Formatting.Indented);
                    Log.TextEntry(cog);

                    if (cog.Contains("ReviewRecommended\": true"))
                    {
                        // "ReviewRecommended": true
                        Log.TextEntry("#############");
                        Log.TextEntry("#### Warning:");
                        Log.TextEntry("#### Review");
                        Log.TextEntry("#### Recommended");
                        Log.TextEntry("#############");
                        return bad;
                    }
                    else
                    {
                        return good;
                    }
                }
            }
            catch (Exception e)
            {
                Log.Exception(e);
                return glitch;
            }
        }


        static void Print(String text = "")
        {
            string message = DateTime.Now.ToString("yyyyMMddHHmmssffff: " + Environment.NewLine) + text;
            Log.TextEntry(message);
        }


        // Wraps the creation and configuration of a Content Moderator client.
        public static class Clients
        {
            // The base URL fragment for Content Moderator calls.
            // Add your Azure Content Moderator endpoint to your environment variables.
            private static readonly string AzureBaseURL = myEndpoint;

            // Your Content Moderator subscription key.
            // Add your Azure Content Moderator subscription key to your environment variables.
            private static readonly string CMSubscriptionKey = mySubscriptionKey;

            // Returns a new Content Moderator client for your subscription.
            public static ContentModeratorClient NewClient()
            {
                // Create and initialize an instance of the Content Moderator API wrapper.
                ContentModeratorClient client = new ContentModeratorClient(new ApiKeyServiceClientCredentials(CMSubscriptionKey));

                client.Endpoint = AzureBaseURL;
                return client;
            }
        }

    }
}

```

**Pull request closed without merging**
