### PR TITLE
Reduce Qt5 requirements to a minimum

### PR DESCRIPTION
**Pull request by luigino**
Fixes https://github.com/projectM-visualizer/projectm/issues/172

### CODE REVIEW

**Comment by revmischa** [comment]
OSX still not happy with this but maybe nothing will make it happy
```
checking for Qt... Info: creating stash file /var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/.qmake.stash
Cannot find file: tmp.90glcrYi.
make: *** [/var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/tmp.1qp1Sui1] Error 2
Cannot find file: tmp.90glcrYi.
make: *** [/var/folders/n8/rmzyc9yx2zvbc978_p6y_by40000gn/T/tmp.1qp1Sui1] Error 2
yes:
    QT_CXXFLAGS= 
    QT_DIR=/Users/cyber/dev/Qt/5.12.1/clang_64/lib
    QT_LIBS= 
    QT_UIC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/uic
    QT_MOC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/moc
    QT_RCC=/Users/cyber/dev/Qt/5.12.1/clang_64/bin/rcc
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```

**Comment by sergiomb2** [comment]
the commit "Extend the search path for Qt-related tools" seems correct , I will test in soon .
The other commit no , btw when a new version of autoconf-archive arrive , we may drop these copies 
of autoconf-archive [1] (and on build require new autoconf-archive package)

[1]
https://github.com/autoconf-archive/autoconf-archive

**Comment by revmischa** [comment]
Is this good to merge?

**Comment by sergiomb2** [comment]
only https://github.com/projectM-visualizer/projectm/pull/173/commits/3c431fc43e8318bdcd48b66eb50e07655e915f80 is good to merge , IMO.

**Comment by revmischa** [comment]
@luigino ?

**Comment by sergiomb2** [comment]
@luigino  I'm studying this [1],  it works, but it is an hack !
we should try improve it which pkg_check_modules [1]  I guess

[1]
https://autotools.io/pkgconfig/pkg_check_modules.html

**Comment by luigino** [comment]
I'll admit that checking for the Qt5 path in configure.ac is not the cleanest thng in the world.
Perhaps it should be done in the relevant m4, but I failed.

**Comment by sergiomb2** [comment]
I asked on stackoverflow and best answer [1] looks like more or less the same ... 

https://stackoverflow.com/questions/55893794/modify-path-from-configure-ac/55904423#55904423

**Comment by luigino** [comment]
@sergiomb2 
perhaps you should have asked how to expand the search path from a m4 file.

**Comment by sergiomb2** [comment]
```
QT5BIN_PATH=$(pkg-config --variable=host_bins Qt5Core)
# ... check for error / validate result ...
PATH=${QT5BIN_PATH}:${PATH}
export PATH
```

**Comment by sergiomb2** [comment]
> Which is more or less what [3c431fc](https://github.com/projectM-visualizer/projectm/commit/3c431fc43e8318bdcd48b66eb50e07655e915f80) does.

Yes , I began the comments, today, with the same statement and I don't  know better .

**Comment by coast77777777777** [comment]
@revmischa merge? or close? we can merge then fix to welcome @luigino contributions.
QT5 build is rather broken regardless of build scripts. For my computers, the visuals operate with my 2080TI in QT5, but the fps drops to unusable for my geforce 780TI. Something is not functioning already.

**Comment by revmischa** [comment]
ok fuck it YOMO (you only merge once)

**Pull request merged**
