### PR TITLE
Check if active preset output texture is valid before copying

### PR DESCRIPTION
**Pull request by hack-s**
Possible fix for https://github.com/projectM-visualizer/projectm/issues/823

### CODE REVIEW

**Review by revmischa — COMMENTED** [review]
comments would be cool! what is Type

**Comment by hack-s** [comment]
I think a better fix would be using a `nullptr` for output texture instead of initializing it empty. But that would be a more intrusive change.

**Comment by kblaschke** [comment]
> I think a better fix would be using a `nullptr` for the output texture initially instead of initializing it empty. But that would be a more intrusive change.

I absolutely don't mind intrusive changes if they are cleaner. If there's no texture, we can surely leave the shared pointer empty. Easier to check, and not more complicated to initialize it later.

If you want to make this change, please do so, that'd be highly appreciated!

**Comment by kblaschke** [comment]
Issue comes from a preset not having an output texture yet (e.g. framebuffer color attachment is not yet initialized), so the texture has to be there, but will be created when the framebuffer is resized to something larger than 0x0, which happens on the first frame draw call.

Applied a fix to check for an empty texture ID in CopyTexture, and openend PRs #826 and #827, closing this one here.

**Pull request closed without merging**
